### ISSUE TITLE
Incorrect convective gain data

### ISSUE THREAD

**Issue by dhblum** [JavierArroyoBastida/EmulatorRSH#1]
In ``models/generate_data.py`` line 37 specifies ``ConOcc = 73``.  However, the model specifies occupancy gains with a sensible gain of 73 W and a radiant fraction of 0.6.  This should mean that convective gain is (1-0.6)*73=29.2 and radiant gain is 0.6*73=43.8 for one occupant.

**Comment by javiarrobas** [comment]
@dhblum you're totally right. Addressed in https://github.com/JavierArroyoBastida/EmulatorRSH/commit/6c0e79e88d56dbaa44a873cb60812c1fdb9fcb95.

**Comment by dhblum** [comment]
That's right, thanks.
